@startuml Activity_Admin_AccountVerification
title Quản Trị - Xác Thực Tài Khoản

start

:Vào "Xác thực tài khoản";

:Xem danh sách ứng viên chờ xác thực;

:Chọn ứng viên;

if (Email hợp lệ?) then (Có)
  :Xác thực tài khoản;
  :Gửi thông báo xác thực;
else (Không)
  :Từ chối đăng ký;
  :Gửi lý do từ chối;
endif

:Xem danh sách nhà tuyển dụng chờ xác thực;

:Chọn nhà tuyển dụng;

if (Thông tin hợp lệ?) then (Có)
  :Xác thực tài khoản;
else (Không)
  :Từ chối đăng ký;
endif

stop

@enduml
