@startuml Activity_Admin_MonitoringAnalytics
title Quản Trị - Giám Sát & Phân Tích

start

:Click "Thống kê & báo cáo";

:Xem thống kê hệ thống;
:Tổng người dùng, công ty, công việc, đơn;

:Xem tăng trưởng người dùng;

:Xem thống kê tin tuyển dụng;

:Xem thống kê ứng tuyển;

:Xem thống kê phỏng vấn;

:Xuất báo cáo (Excel, PDF);

stop

@enduml
