@startuml UC21_Activity
'https://plantuml.com/activity-diagram-beta

start
:Quan tri vien mo danh sach tin cho kiem duyet;
:Chon tin tuyen dung can xu ly;
:Kiem tra noi dung va tieu chi chinh sach;
if (Tin dat yeu cau?) then (yes)
  :Phe duyet va cho phep hien thi;
else (no)
  :Dong hoac tu choi tin;
  :Ghi ly do vi pham;
endif
:Gui thong bao ket qua cho nha tuyen dung;

stop

@enduml