@startuml UC21_Activity
'https://plantuml.com/activity-diagram-beta

start
:Quan tri vien mo danh sach tin cho kiem duyet;
:Chon tin tuyen dung can xu ly;
:Xem chi tiet tin va doi chieu chinh sach;
if (Tin vi pham?) then (yes)
  :Dong tin;
  :Ghi ly do vi pham;
  :Gui thong bao cho nha tuyen dung;
else (no)
  :Khong thay doi trang thai tin;
endif

stop

@enduml